name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Data
        run: echo "${{ toJSON(github) }}"
      - name: Get code
        uses: action/checkout@v3
      - name: Install Dependencies
        run: cd demo-project-events && npm ci
      - name: Build & Test
        run: cd demo-project-events && npm run build && npm run test

