name: React App Demo Actions
on:
  push:
    branches:
      - 'rect-app-demo'
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Check Node JS Version
        run: node --version

      - name: Switch to React app
        run: cd react-app && ls -l

      - name: Install Dependencies
        run: npm ci

      